main:
    project: 'lane_mp'
    dataset: 'paloalto'
    version: 'none'
    disable_wandb: True
paths:
    home: /home/zuern/
    package: /home/zuern/lane-segmentation/
    dataroot: /home/zuern/datasets/lane-segmentation/data_sep/
    dataroot_ssd: /home/zuern/datasets/lane-segmentation/data_sep/
    checkpoints: /home/zuern/lane-segmentation/checkpoints/lanenet/
    rel_dataset: all/010922-large/
    split: train
    config_name: n500-halton-endpoint-010922-large
preprocessing:
    gt_pointwise: True
    sampling_method: halton
    num_node_samples: 500
    edge_proposal_method: random  # triangular or random
    N_interp: 3
    k_waypoints: 1
    visualize: False
    angle_penalty: 1 # not utilized yet
    context_regressor_ckpt: lanenet/centerlines-sdf-context_sweet-snowflake-44_e_024_acc_0.503.pth  # resnet152 010922-large
    ego_regressor_ckpt: lanenet/centerlines-sdf-ego-context_radiant-dawn-46_e_011_acc_0.318.pth  # resnet152 010922-large
    ego_regressor_num_channels: 4
model:
    dataparallel: True
    device: cuda
    batch_size: 2
    lr: 1e-3
    beta_lo: 0.9
    beta_hi: 0.999
    num_epochs: 300
    gnn_depth: 6
    # lane_mpnn_node
    #map_feat_dim: 128
    #node_dim: 48
    #edge_dim: 32
    #msg_dim: 32
    #edge_geo_dim: 32 #(but not used, only um nicht confused zu werden)
    # lane_mpnn_att
#    map_feat_dim: 256 #(= edge_geo_dim)
#    node_dim: 48
#    edge_dim: 32
#    msg_dim: 32
#    edge_geo_dim: 256 #(=map_feat_dim)
    # lane_mpnn
    map_feat_dim: 64
    node_dim: 16
    edge_dim: 32
    msg_dim: 32
    edge_geo_dim: 16
    # end_of_archs
    in_channels: 4  # number of channels of image
    loader_workers: 4
    weight_decay: 1e-4 #0.0001
#    checkpoint: lane-segmentation/checkpoints/lanemp_laced-microwave-29_026.pth
    checkpoint: lane-segmentation/checkpoints/lanemp_light-voice-343_026.pth  # 010922-large ALL cities
driving:
    mode: multiple # single or multiple
    cuda: true
    render_onscreen: false
    output_dir: /data/lane-segmentation/drive_freely_output/
    #satellite_image_path: /home/zuern/Desktop/cvpr-viz/mia_580-30878.png
    #satellite_image_path: /home/zuern/UnofficialLaneExtraction/mia_test_2000-43800.png
    #satellite_image_path: /home/zuern/Desktop/cvpr-viz/mia_2324-39156.png
    #satellite_image_path: /home/zuern/Desktop/cvpr-viz/mia_7756-38748.png
    #satellite_image_path: /home/zuern/Desktop/cvpr-viz/mia_17548-9692.png
    satellite_image_path: /home/zuern/UnofficialLaneExtraction/mia_test_42000-23500.png
    #starting_pose: [ 2789, 3020, 8 * np.pi / 4 ]
    #poses_path: /home/zuern/UnofficialLaneExtraction/dataset_argoverse2/test_tiles/mia_test_2000-43800_init_poses.json
    poses_path: /home/zuern/UnofficialLaneExtraction/dataset_argoverse2/test_tiles/mia_test_42000-23500_init_poses_filt.json
    # DRIVE-AGG PARAMETERS
    threshold_px: 80                # local agg graph euclidean distance threshold
    threshold_rad: 0.5              # local agg graph angular distance threshold
    non_drivable_thresh: 0.15    # drivable corridor threshold used for node sampling
    closest_lat_dist_succ: 30       # in-drive lateral aggregation pixel threshold
    closest_lat_dist_agg: 20        # among-drive lateral aggregation pixel threshold
    w_decay: false
    max_steps: 30                   # maximum number of among-branch steps
    max_branch_age: 10              # maximum number of in-branch steps
    smooth_pred_graph: true         # should the predicted graph be laplace-smoothed before aggregating
    remove_smp: true                # remove parallel paths and unvalited splits and merges
    max_branch_id: 3                # maximum number of branches
